apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: say-hello
spec:
  params:
  - name: contenttype
    description: The Content-Type of the event
    type: string
  workspaces:
    - name: git-source
      #      mountPath: /workspace
  steps:
  - name: say-hi
    image: bash
    command: ["bash", "-c"]
    args:
      - echo -e 'Hello Triggers!\nContent-Type is $(params.contenttype)'
