apiVersion: demo.example.com/v1alpha1
kind: Nginx
metadata:
  name: nginx-sample11
spec:
  # Default values copied from <project_dir>/helm-charts/nginx/values.yaml
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  fullnameOverride: ""
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/ravindra_be2004/mydemo
    tag: "v1"
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: ""
    enabled: true
    hosts:
    - host: mydemo.apps.ocp4.example.com
      paths:
      - path: /
        pathType: Prefix
    tls: []
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    port: 8080
    type: ClusterIP
  serviceAccount:
    annotations: {}
    automount: true
    create: true
    name: ""
  tolerations: []
  volumeMounts: []
  volumes: []
  
  
