---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: foo-trig
      interceptors:
      - cel:
          filter: "(header.match('X-GitHub-Event', 'push') && body.action == 'opened' || body.action == 'synchronize' || body.action == 'close')"
      bindings:
        - ref: message-binding
      template:
        ref: pipeline-template
