apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-role
rules:
- apiGroups:
  - ""
  resources:
    #  - namespaces
  - configmaps
  - pods
  verbs:
  - get
  - list
  - watch  

